### ISSUE TITLE
2.0.0-dev.2 Questions and Feedback

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#129]
#### Question Panels
1. Is the current design for the question panels fine, or will it be better if they are all displayed at the same time with a scroll bar? (Image 1)

#### Theme Analysis panel
1. Should a summary be written by the student to be carried over for People ID, Dreams, Spoken words and Passion?
2. Where should the MBTI info be displayed? (Image 2)

#### Career Guidance Panel
1. Are the themes carried over from the theme analysis page in read only format, or are they separate themes related to the Career Guidance? (Image 3)
2. The website for the career test no longer displays "Sub Interests", can these be removed from the Career Test Results widget?

#### PDF output
1. Can you please provide us with an example format for the PDF generated from the Theme Analysis, Career Guidance, and Mission panel?

### TODO
- [ ] Add email address to details panel
- [ ] Career Orientation Panel
- [ ] Career Guidance Panel
- [ ] Mission Statement Panel
### Images
1. Questions Panel
![questions](https://user-images.githubusercontent.com/5778739/34940117-077f4536-f9f7-11e7-8c6d-aa4a0f27fbca.png)

2. MBTI info
![mbti_info](https://user-images.githubusercontent.com/5778739/34937812-c89a83ba-f9ee-11e7-988e-7087201b2aec.png)

3. Career Guidance Panel
![career guidance](https://user-images.githubusercontent.com/5778739/34937949-39800e74-f9ef-11e7-95cb-afe994ed6cef.jpg)

**Comment by egeldenhuys** [comment]
See new issues.
