### ISSUE TITLE
TODO: Style Panels

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#30]
Currently the panels only Load from markdown, Display Elements, Load userdata, save userdata.
They look bad and have no style.

#### Panels
- [ ] Details
- Assessments
  - [ ] External (MBTI, Life Keys, Career test results)
  - [ ] Roles
  - [ ] Skills
  - [ ] Passion
  - [ ] Dreams
  - [ ] People
  - [ ] Values
  - [ ] Priorities (Ordered Container)
  - [ ] People Orientation
  - [ ] Spoken Words
  - [ ] Work Environment
  - [ ] Career Orientation (`CheckBoxContainerWithTitle`)
- [ ] Themes Analysis
- [ ] Career guidance
- [ ] Mission statement
