### ISSUE TITLE
TODO: Add Basic Panels

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#31]
List of panels that have been merged into develop

#### Panels
- [x] Details
- Assessments
  - [ ] External (MBTI, Life Keys, Career test results)
@quantum-sicarius
  - [X] Roles
  - [X] Skills
  - [X] Passion
  - [X] Dreams
  - [X] People
  - [X] Values
  - [x] Priorities (Ordered Container)
@egeldenhuys
  - [X] People Orientation
  - [X] Spoken Words
  - [ ] Work Environment
  - [ ] Career Orientation (`CheckBoxContainerWithTitle`)
- [ ] Themes Analysis
- [ ] Career guidance
- [ ] Mission statement
