### ISSUE TITLE
Details and External Panel

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#36]
### Details Panel
(To be copied to the Mission statement tab automatically)

#### Fields (See project as at fe7f9986d2877a7df16bfdeea78784b0f7f1e322)
- Name & Surname
- Date
- Age
- Email Adress

#### Fields
- [MBTI](https://github.com/egeldenhuys/prothesis-2/wiki/Careers-for-MBTI)
- [Life Keys](https://github.com/egeldenhuys/prothesis-2/wiki/Life-Keys) (3)
- Career Test Results (Not sure what this is, will post when I remember)

### TODO
- [ ] Create base `components` that will be used.
  - [ ] Need a Drop down selection for Life Keys and MBTI (Load from markdown)
- [ ] Create Panel `.js` and `.html`. In this case the panel will store the state.
- [ ] Create the markdown files for generating the GUI (See wiki for GUI elements for MBTI and Life Keys)
- [ ] Load the GUI elements from markdown
- [ ] Initialise the components
- [ ] Inject .html
- [ ] Inject components
- [ ] Register panel with `DataManager` in `index.js`
