### ISSUE TITLE
Priorities Panel

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#37]
See the [wiki](https://github.com/egeldenhuys/prothesis-2/wiki/Passion-ID-Dreams#priorities-in-order) for the list of priorities

---- 

### TODO
- [ ] Create a markdown file in `gui/Assessments/` to represent the GUI.
    - Example Format. See existing `.md` files in `gui/`
    ``` 
    > TYPE:
    > OrderedItemContainer
    >
    > FORMAT:
    > ### [Title]
    > - <Item>
    > - <Item>
    ```
- [ ] Create an `OrderedItem` `Component` in `gui.js`. (See Possible Component Design below). 
The `OrderedItem`
- [ ] Create an `OrderedItemContainer` `Component` in `gui.js`. The container should keep track of the order internally. The `onchange` event on `OrderedItem` should be linked to a function in `OrderedItemContainer` in order to keep the internal state up to date. Similar to the `CheckBoxContainer`
  - [ ] As the rank of the priority changes, its position in the `Container` should also change.
- [ ] Follow the pattern in `app/panels/assessments/` to create a `.html` and `.js` for the `Priorities Panel`
- [ ] Add the panel tab to `index.html`
- [ ] Create an `OrderedItemPanel`
  - [ ] Inject the `.html` into `index.html`
  - [ ] Load the GUI from file
  - [ ] Create the `OrderedItemContainer` from the loaded GUI
  - [ ] Style the `OrderedItemContainer`
  - [ ] Inject the `OrderedItemContainer` into `index.html`

### Possible `Component` Design
![priorities](https://user-images.githubusercontent.com/5778739/27957620-84058026-631f-11e7-84ae-c6d827943458.png)
