### ISSUE TITLE
Core - Loading and saving of GUI and user data

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#61]
The proccess is as follows:
1. Load GUI elements from file
2. Load user data
3. Save user data
4. Repeat

### TODO
- [x] GUI representation in config files
- [x] Generating the GUI from the config files
- [x] How will we save and load the user data?

### New Implementation
- The ideal would be to fully describe the GUI in terms of configuration files ([TOML](https://github.com/toml-lang/toml) looks nice). This way Target Life can modify the entire interface without recompiling (**Future Issue**: Where will this file be stored?)
- We can define basic components and their properties, until we can generate the entire GUI from these config files
- Example (Not proper format):
```toml
[details]
type = "panel"
title = "Details"

[details_column]
type = "col"
rows = 1
cols = 2
row_height = 46
col_width = "equal"
parent = "details"

[txt_name]
type = "textbox"
title = "Name"
parent = "details_column"

[panel_many]
type = "panel"
title = "Many Checks"

[[panel_many_checkboxes]]
type = "checkbox_container"
parent = "panel_many"

[[panel_many_checkboxes.contents]]
title = "The Box"
tooltip = "A box?"

[[panel_many_checkboxes.contents]] # Is this allowed in TOML?
title = "A box too many"
tooltip = "Moar box"
```

### nodejs implementation
- Only strings can be modified, not the entire GUI layout
- GUI elements are stored in multiple JSON files, sorted according to panel
- The Data Manager concatenates all the files and sends the JSON blob to all the panels
    - Each panel is registered to read a specific key
    - The panel then dynamically generates the GUI based on implicit rules
- The Data Manager then loads the User Data file and sends the JSON blob to each panel
    - The panel populates the GUI based on the key value pairs in the JSON blob
- A Panel has the following interface
    - `setGUIState(JSON state)`
    - `setUserDataState(JSON state)`
    - `JSON getUserData()`

#### UML (Might be outdated)
[View on Google Drive](https://docs.google.com/drawings/d/1IYfb5ZCsqpyMEdmWWJM-ekHK8TG8c2kYUp_mjceMG5Q/edit?usp=sharing)

**Comment by egeldenhuys** [comment]
Working on a prototype in `proto-gui-config`

**Comment by egeldenhuys** [comment]
If we want to allow every aspect of the GUI to be modified we should use electron and HTML or use [XRC](http://docs.wxwidgets.org/3.0/overview_xrc.html). However the full flexibility also comes with full complexity. I therefore propose we use a system similar to the one we currently have.

Example TOML:
```toml
[[passions]]
text = "nodejs"
tooltip = "You LOVE working with node"

[[passions]]
text = "HTML"
tooltip = "Working 8 hours a day with HTML makes you come alive"

[[dreams]]
text = "What makes you come alive"
[[dreams]]
text = "node?"
```

This will allow Target Life to add, remove and edit most of the elements in a sane way.

**Comment by egeldenhuys** [comment]
Managed to get a [prototype](https://github.com/prothesis-software/prothesis-2/tree/proto-gui-config/prototypes/proto-gui) working that creates buttons based on the contents of a .toml file. 
Using [cpptoml](https://github.com/skystrife/cpptoml) to parse toml.

Code works on Linux and Windows.
